name: zdebts_api
description: Um projeto de estudos de Dart para construção de API.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  mongo_dart: ^0.4.4
  mysql1: ^0.17.1
  shelf: ^0.7.5
  shelf_router: ^0.7.4

dev_dependencies:
  test: ^1.15.0
